### ISSUE TITLE
GpioBridge as an interface

### ISSUE THREAD

**Issue by brunoluiz** [eitch/ch.eitchnet.beaglebone#1]
Making GpioBridge as an interface will enable developers to mock it for JUnit tests

**Comment by eitch** [comment]
Hi, do you want to send me a pull request? Or should i do it?

**Comment by eitch** [comment]
Btw, using Mockito you can also mock a class, not just an interface.

**Comment by brunoluiz** [comment]
Well, as far as I know, mocking concrete classes is not recommended. In this case, I know it have to be an interface to be mocked properly, but I am not sure if it is right to have an interface of a Singleton.

**Comment by eitch** [comment]
Ahh, you are right. Sorry, i forgot it was a singleton... Do you want to do the changes, or should i do it?

**Comment by eitch** [comment]
Singletons aren't such a good thing anyhow... =))

**Comment by brunoluiz** [comment]
I tried a solution here, it seems to work... I will push in a moment

**Comment by brunoluiz** [comment]
I just realized that I messed with the JavaDoc in this push

**Comment by brunoluiz** [comment]
Fixed. Check if it is okay for you.

**Comment by eitch** [comment]
New release 0.1.3 deployed to Maven. Will take a few hours to synch, but you should then have the new version with the interface.
